CREATE TABLE STUDENT_DISCIPLINE (
    CD_STUDENT BIGINT,
    CD_DISCIPLINE BIGINT,
    PRIMARY KEY (CD_STUDENT, CD_DISCIPLINE),
    FOREIGN KEY (CD_STUDENT) REFERENCES Student(CD_STUDENT),
    FOREIGN KEY (CD_DISCIPLINE) REFERENCES Discipline(CD_DISCIPLINE)
);

INSERT INTO STUDENT_DISCIPLINE (CD_STUDENT, CD_DISCIPLINE)
VALUES (1, 1);